const cartActionTypes = {
  CLOSE_CART: "CLOSE_CART",
  TOGGLE_CART: "TOGGLE_CART",
  ADD_ITEM: "ADD_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  INCREASE_QUANTITY_ITEM: "INCREASE_QUANTITY_ITEM",
  DECREASE_QUANTITY_ITEM: "DECREASE_QUANTITY_ITEM",
  CLEAR_CART_ITEMS: "CLEAR_CART_ITEMS",
};

export default cartActionTypes;
